# Generated by Django 3.0.4 on 2020-03-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_overflow', '0003_auto_20200323_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ip_address',
            field=models.CharField(max_length=32),
        ),
    ]
