# Generated by Django 3.0.4 on 2020-03-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_overflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='belief',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='headache',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
