# Generated by Django 3.0.4 on 2020-03-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_overflow', '0002_auto_20200322_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='cough',
            new_name='coughing',
        ),
    ]
